project:
  id: "open-targets-genetics-dev"
files:
  # Peaks file normalized
  peaks: gs://genetics-portal-dev-analysis/ba13/OTAR034_CHEERS_epimap_Jul22/Full_epimap_adjusted.txt
  #SNPs file
  snp: gs://genetics-portal-dev-analysis/ba13/OTAR034_CHEERS_epimap_Jul22/example_GCST004131
  # Output stat
  out_stats: gs://genetics-portal-dev-analysis/ba13/OTAR034_CHEERS_epimap_Jul22/example_GCST004131_out_stat
  # Output peaks
  out_unique_peaks: gs://genetics-portal-dev-analysis/ba13/OTAR034_CHEERS_epimap_Jul22/example_GCST004131_out_peaks
  # Output peaks overlap
  out_snp_peak_overlaps: gs://genetics-portal-dev-analysis/ba13/OTAR034_CHEERS_epimap_Jul22/example_GCST004131_out_overlaps