project:
  id: "open-targets-genetics-dev"
files:
  # sumstats to munge
  input_sumstats:
  # hapmap3 SNPs to join with munge
  w_hm3_snps:
  # sumstats as ldsc inputs
  munged_sumstats:
  # ldscores (European)
  ref_ld_chr:
  # weights
  w_ld_chr:
